[package]
name = "clause"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
clause-macro = { path = "./macro" }
clause-parser = { path = "./parser" }
