[package]
name = "module"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
matcher = { path = "../matcher" }
vm = { path = "../vm" }
