[package]
name = "ogma"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
ogma-libs = { version = "0.1", path = "../libs" }
ogma-macros = { version = "0.1", path = "../macros" }
object-query = { version = "0.1" }
